#ifndef HEADERS_HPP
#define HEADERS_HPP

enum Header
{
    CMSG_MESSAGE_LEGER = 0,
    CMSG_PING = 1,
    CMSG_PONG = 2,
    CMSG_MESSAGE_CUSTOM = 3,

    SMSG_PONG = 4,
    SMSG_PING = 5,
    SMSG_KICK = 6,

    /** Custom Messages Clients **/
    CMSG_MESSAGE_AUTH = 7,
    CMSG_MESSAGE_HOMEWORKFOR = 8,
    CMSG_MESSAGE_CHAT_CLASSE = 9,
    CMSG_MESSAGE_CHAT_CANAL = 10,
    CMSG_MESSAGE_PRIVATE_MESSAGE = 11,
    CMSG_MESSAGE_LISTMATIERE = 12,
    CMSG_MESSAGE_SHOW_ME_CONNECTED = 13,
    CMSG_COMMAND_ADMIN = 14,

    /** Custom Messages Server **/

    SMSG_AUTHENTIFICATION_SUCCESS = 15,
    SMSG_AUTHENTIFICATION_FAILED = 16,
    SMSG_HOMEWORK = 17,
    SMSG_YOU_ARE_NOT_AUTHENTIFIED = 18,
    SMSG_MESSAGE_CHAT_PRIVATE = 19,
    SMSG_MESSAGE_CHAT_CANAL = 20,
    SMSG_MESSAGE_CHAT_CANAL_SYSTEM = 21,
    SMSG_MESSAGE_CHAT_SYSTEM = 22,
    SMSG_LISTMATIERE = 23,
    SMSG_COMMAND_REPONSE = 24,
    SMSG_COMMAND_REFUSED = 25,

    COUNT = SMSG_COMMAND_REFUSED + 1
};

#endif // HEADERS_HPP
